# Test 2024-04-07 at 22:25:21

name: Test

on:
  push

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'

    - name: Install Tree
      run:
        sudo apt install tree

    - name: Tree
      run:
        tree

    - name: Test Math Intersection Circle Line
      run:
        prove -Idtt/lib -Ilib
