# Test 2024-03-14 at 00:09:26

name: Test

on:
  push

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/DataTableText
        path: dtt

    - name: Install Tree
      run:
        sudo apt install tree

    - name: Tree
      run:
        tree

    - name: Cpan
      run:  sudo cpan install -T Data::Dump

    - name: Test Math Intersection Circle Line
      run:
        perl -Idtt/lib lib/Math/Intersection/Circle/Line.pm
